//! Compiles `content/posts/*.md` into a static `POSTS` table.
//!
//! Frontmatter is parsed and markdown is rendered to HTML here, at build time,
//! so the server does no I/O and no markdown parsing at runtime and the binary
//! is self-contained — there is no `content/` directory to deploy alongside it.
//!
//! The generated table is compiled only into the `ssr` build. See the note on
//! `POSTS` below.

use comrak::{
    Options, markdown_to_html_with_plugins, options::Plugins, plugins::syntect::SyntectAdapter,
};
use gray_matter::{Matter, engine::YAML};
use serde::Deserialize;
use std::{env, fmt::Write as _, fs, path::Path};

#[derive(Deserialize)]
struct FrontMatter {
    title: String,
    kind: String,
    category: Option<String>,
    image: Option<Image>,
    website: Option<String>,
    published: Option<String>,
    started: Option<String>,
    completed: Option<String>,
    updated: Option<String>,
    #[serde(default)]
    draft: bool,
}

#[derive(Deserialize)]
struct Image {
    src: String,
    alt: Option<String>,
}

fn main() {
    println!("cargo:rerun-if-changed=content/posts");
    println!("cargo:rerun-if-changed=build.rs");

    let dir = Path::new("content/posts");
    let matter = Matter::<YAML>::new();

    // `None` emits CSS classes rather than inline styles, so code blocks can
    // follow the light/dark theme. The matching stylesheet is generated in the
    // design phase; until then code blocks render structured but unstyled.
    let adapter = SyntectAdapter::new(None);
    let mut plugins = Plugins::default();
    plugins.render.codefence_syntax_highlighter = Some(&adapter);

    let mut options = Options::default();
    options.extension.strikethrough = true;
    options.extension.table = true;
    options.extension.autolink = true;
    options.extension.footnotes = true;
    // Enables heading anchors, so posts can be deep-linked.
    options.extension.header_id_prefix = Some(String::new());
    // Posts contain hand-written HTML (e.g. the <img> grids in tetanes.md),
    // which is dropped unless raw HTML is allowed through. Safe here: the
    // markdown is ours and is rendered at build time, never from user input.
    options.render.r#unsafe = true;

    let mut posts = Vec::new();
    let mut entries: Vec<_> = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display()))
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "md"))
        .collect();
    entries.sort();

    for path in entries {
        let slug = path.file_stem().unwrap().to_string_lossy().into_owned();
        let raw = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));

        let parsed = matter
            .parse::<FrontMatter>(&raw)
            .unwrap_or_else(|e| panic!("{}: bad frontmatter: {e}", path.display()));
        let fm = parsed
            .data
            .unwrap_or_else(|| panic!("{}: missing frontmatter", path.display()));

        if fm.kind != "blog" && fm.kind != "project" {
            panic!("{}: kind must be \"blog\" or \"project\"", path.display());
        }

        let body_html = markdown_to_html_with_plugins(&parsed.content, &options, &plugins);
        // ~200 wpm, the usual reading-speed approximation. Replaces the
        // hand-maintained `minutesToRead` field from the old JSON.
        let words = parsed.content.split_whitespace().count();
        let reading_minutes = words.div_ceil(200).max(1);

        posts.push((slug, fm, body_html, reading_minutes));
    }

    // Newest first. Sorting here means the runtime never parses a date to order
    // a listing. Undated drafts sort last.
    posts.sort_by(|a, b| {
        b.1.published
            .as_deref()
            .unwrap_or("")
            .cmp(a.1.published.as_deref().unwrap_or(""))
    });

    let mut out = String::new();
    out.push_str(
        r#"// @generated by build.rs from content/posts/*.md — do not edit.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Kind {
    Blog,
    Project,
}

#[derive(Debug, Clone, Copy)]
pub struct Image {
    pub src: &'static str,
    pub alt: &'static str,
}

#[derive(Debug, Clone, Copy)]
pub struct Post {
    pub slug: &'static str,
    pub title: &'static str,
    pub kind: Kind,
    pub category: Option<&'static str>,
    pub image: Option<Image>,
    pub website: Option<&'static str>,
    /// RFC 3339, e.g. "2020-01-31T21:19:14Z".
    pub published: Option<&'static str>,
    pub started: Option<&'static str>,
    pub completed: Option<&'static str>,
    pub updated: Option<&'static str>,
    pub draft: bool,
    pub reading_minutes: usize,
    pub body_html: &'static str,
}

"#,
    );

    // Only the `ssr` build gets the post bodies. Under `hydrate` this is an
    // empty slice, which keeps ~26 posts of rendered HTML out of the WASM
    // bundle while letting server-only components still typecheck for wasm32.
    // Nothing observes the empty table: in islands mode `#[component]` bodies
    // never run in the browser.
    out.push_str("#[cfg(not(feature = \"ssr\"))]\npub static POSTS: &[Post] = &[];\n\n");
    out.push_str("#[cfg(feature = \"ssr\")]\npub static POSTS: &[Post] = &[\n");
    for (slug, fm, body_html, reading_minutes) in &posts {
        let kind = if fm.kind == "blog" {
            "Kind::Blog"
        } else {
            "Kind::Project"
        };
        writeln!(out, "    Post {{").unwrap();
        writeln!(out, "        slug: {},", lit(slug)).unwrap();
        writeln!(out, "        title: {},", lit(&fm.title)).unwrap();
        writeln!(out, "        kind: {kind},").unwrap();
        writeln!(out, "        category: {},", opt(fm.category.as_deref())).unwrap();
        match &fm.image {
            Some(img) => writeln!(
                out,
                "        image: Some(Image {{ src: {}, alt: {} }}),",
                lit(&img.src),
                lit(img.alt.as_deref().unwrap_or(""))
            )
            .unwrap(),
            None => writeln!(out, "        image: None,").unwrap(),
        }
        writeln!(out, "        website: {},", opt(fm.website.as_deref())).unwrap();
        writeln!(out, "        published: {},", opt(fm.published.as_deref())).unwrap();
        writeln!(out, "        started: {},", opt(fm.started.as_deref())).unwrap();
        writeln!(out, "        completed: {},", opt(fm.completed.as_deref())).unwrap();
        writeln!(out, "        updated: {},", opt(fm.updated.as_deref())).unwrap();
        writeln!(out, "        draft: {},", fm.draft).unwrap();
        writeln!(out, "        reading_minutes: {reading_minutes},").unwrap();
        writeln!(out, "        body_html: {},", lit(body_html)).unwrap();
        writeln!(out, "    }},").unwrap();
    }
    out.push_str("];\n");

    let dest = Path::new(&env::var("OUT_DIR").unwrap()).join("content.rs");
    fs::write(&dest, out).unwrap_or_else(|e| panic!("cannot write {}: {e}", dest.display()));
}

/// Emit a Rust string literal. Post bodies contain `"`, `\`, `#` and `{}` in
/// arbitrary combinations, so escape rather than trying to pick a raw-string
/// hash count.
fn lit(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

fn opt(s: Option<&str>) -> String {
    match s.filter(|v| !v.is_empty()) {
        Some(v) => format!("Some({})", lit(v)),
        None => "None".into(),
    }
}
