[package]
name = "lukeworks"
version = "0.1.0"
edition = "2021"
default-run = "lukeworks"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
chrono = { version = "0.4.24", features = ["serde"] }
leptos = { version = "0.2.5", default-features = false, features = ["stable"] }
leptos_meta = { version = "0.2.5", default-features = false }
leptos_dom = { version = "0.2.5", default-features = false }
leptos_router = { version = "0.2.5", default-features = false, features = ["stable"] }

# dependecies for client (enable hydrate set)
wasm-bindgen = { version = "0.2.83", optional = true }
console_log = { version = "0.2.0", optional = true }
console_error_panic_hook = { version = "0.1.7", optional = true }

# dependecies for server (enable when ssr set)
actix-files = { version = "0.6.2", optional = true }
actix-web = { version = "4.3.1", features = ["rustls"], optional = true }
futures = { version = "0.3.25", optional = true }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = { version = "1.0.91", optional = true }
reqwest = { version = "0.11.13", features = ["json"], optional = true }
leptos_actix = { version = "0.2.5", optional = true }
dotenvy = { version = "0.15.6", optional = true }
tracing = { version = "0.1.37", optional = true }
log = "0.4.17"

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'

[features]
default = ["ssr"]
hydrate = ["leptos/hydrate", "leptos_meta/hydrate", "leptos_router/hydrate", "dep:wasm-bindgen", "dep:console_log", "dep:console_error_panic_hook"]
ssr = ["leptos/ssr", "leptos_meta/ssr", "leptos_router/ssr", "dep:leptos_actix", "dep:reqwest", "dep:actix-web", "dep:actix-files", "dep:futures", "dep:tracing", "dep:serde_json", "dep:dotenvy"]

[package.metadata.leptos]
