[package]
name = "lukeworks"
version = "0.1.0"
edition = "2021"
default-run = "lukeworks"
resolver = "2"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["ssr"]
hydrate = ["dep:console_error_panic_hook", "dep:console_log", "dep:log", "dep:wasm-bindgen"]
ssr = ["dep:axum", "dep:leptos_axum", "dep:serde_json", "dep:tokio", "dep:tower", "dep:tower-http", "dep:tracing-subscriber"]
perf = []

[dependencies]
anyhow = "1.0.72"
cfg-if = "1.0.0"
chrono = { version = "0.4.26", default-features = false, features = ["clock", "serde", "std"] }
leptos = { version = "0.4.8", features = ["rustls"] }
leptos_meta = { version = "0.4.8" }
leptos_dom = { version = "0.4.8" }
leptos_router = { version = "0.4.8" }
once_cell = "1.18.0"
thiserror = "1.0.44"
tracing = "0.1.37"

# dependecies for client (enabled with `hydrate` feature)
console_error_panic_hook = { version = "0.1.7", optional = true }
console_log = { version = "1.0.0", optional = true }
log = { version = "0.4.19", optional = true }
wasm-bindgen = { version = "0.2.87", optional = true }

# dependecies for server (enabled with `ssr` feature)
axum = { version = "0.6.20", optional = true }
leptos_axum = { version = "0.4.8", optional = true }
serde_json = { version = "1.0.104", optional = true }
serde = { version = "1.0.181", features = ["derive"] }
tokio = { version = "1.29.1", optional = true }
tower = { version = "0.4.13", optional = true }
tower-http = { version = "0.4.3", features = ["fs"], optional = true }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"], optional = true }

[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"

[package.metadata.leptos]
tailwind-input-file = "tailwind.css"
assets-dir = "public"
site-addr = "127.0.0.1:3000"
bin-features = ["ssr"]
lib-features = ["hydrate"]
lib-profile-release = "wasm-release"
