[graph]
all-features = true
no-default-features = false

[output]
feature-depth = 1

[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "warn"
ignore = [
  { id = "RUSTSEC-2024-0320", reason = "dependency of comrak" },
  { id = "RUSTSEC-2025-0141", reason = "dependency of comrak" },
  { id = "RUSTSEC-2026-0173", reason = "dependency of leptos: https://github.com/leptos-rs/leptos/issues/4768" },
  { id = "RUSTSEC-2024-0436", reason = "dependency of leptos: https://github.com/leptos-rs/leptos/issues/3685" },
]

[licenses]
version = 2
allow = [
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  "CC0-1.0",
  "MIT",
  "Unicode-3.0",
  "Unicode-DFS-2016",
  "Zlib",
]
confidence-threshold = 0.8
exceptions = []

[licenses.private]
ignore = true
registries = []

[bans]
multiple-versions = "allow"
wildcards = "deny"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = []
gitlab = []
bitbucket = []
