env_files = [".envrc"]

[env]
VERSION = { script = [
  "awk -F ' = ' '$1 ~ /version/ { gsub(/[\\\"]/, \"\", $2); printf(\"%s\",$2) }' Cargo.toml",
] }

[env.development]
RUST_LOG = "info,lukeworks=debug,tower_http=debug,axum::rejection=trace"

[env.production]
RUST_LOG = "info"

[tasks.default]
alias = "image"

[tasks.version]
description = "Print the crate version"
category = "Tools"
script = ["echo Version: ${VERSION}"]

[tasks.install-deps]
description = "Install wasm target"
command = "rustup"
args = ["target", "add", "wasm32-unknown-unknown"]

[tasks.purge-logs]
description = "Purge all log files"
category = "Tools"
script = ["rm -f logs/*"]

[tasks.clean]
description = "Clean up build artifacts"
category = "Development"
command = "cargo"
args = ["clean", "-p", "lukeworks"]
dependencies = ["purge-logs"]

[tasks.lint]
description = "Lint with clippy"
category = "Development"
command = "cargo"
args = ["clippy"]

[tasks.build]
description = "Build with cargo-leptos"
category = "Build"
command = "cargo"
args = ["leptos", "build", "--release", "-P"]
dependencies = ["install-deps"]

[tasks.run]
description = "Run SSR server in release mode"
category = "Development"
command = "cargo"
args = ["leptos", "serve", "--release", "-P"]
dependencies = ["purge-logs", "install-deps"]

[tasks.dev]
description = "Run SSR server in debug mode"
category = "Development"
command = "cargo"
args = ["leptos", "watch"]
dependencies = ["purge-logs", "install-deps"]

[tasks.test]
description = "Run SSR and client unit tests"
category = "Development"
command = "cargo"
args = ["leptos", "test"]
dependencies = ["install-deps"]

[tasks.image]
description = "Build SSR image for deployment"
category = "Build"
command = "docker"
args = ["build", "--progress", "plain", "-t", "lukeworks:${VERSION}", "."]
dependencies = ["install-deps"]
