apiVersion: apps/v1
kind: Deployment
metadata:
  name: lukeworks
  labels:
    app: lukeworks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lukeworks
  template:
    metadata:
      labels:
        app: lukeworks
    spec:
      containers:
        - name: lukeworks
          image: nginx:alpine
          # resources:
          #   limits:
          #     memory: "128Mi" # 128MB
          #     cpu: "200m" # 200 millicpu (.2 or 20% of the cpu)
          readinessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 3
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 2
