const mockBlogPosts = [
  {
    id: 1,
    url: "/some-test-post",
    thumb: "/images/blog/lost_and_found_part_0.jpg",
    title: "Post 1",
    content: "Testing a post",
    minutesToRead: 5,
    publishedAt: "2020-01-02 08:00:00",
    likes: 5,
    categoryId: 1,
  },
  {
    id: 2,
    url: "/some-test-post-2",
    thumb: "/images/blog/lost_and_found_part_1.jpg",
    title: "Post 2",
    content: "Testing a post 2",
    minutesToRead: 10,
    publishedAt: "2020-01-05 08:00:00",
    likes: 2,
    categoryId: 2,
  },
  {
    id: 3,
    url: "/some-test-post-3",
    thumb: "/images/blog/lost_and_found_part_2.jpg",
    title: "Post 3",
    content: "Testing a post 3",
    minutesToRead: 10,
    publishedAt: "2020-01-05 08:00:00",
    likes: 2,
    categoryId: 2,
  },
  {
    id: 4,
    url: "/some-test-post-4",
    thumb: "/images/blog/lost_and_found_part_3.jpg",
    title: "Post 4",
    content: "Testing a post 4",
    minutesToRead: 10,
    publishedAt: "2020-01-05 08:00:00",
    likes: 2,
    categoryId: 2,
  },
];

export { mockBlogPosts };
