---
name: Outdated

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "10 16 * * 1"

jobs:
  outdated:
    name: Outdated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 17.8.0
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
      - name: Install
        run: npm ci
      - run: npm outdated
